config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'restaurants' => 'restaurants#index'

  resources :restaurants do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user

  validates :name, length: { minimum: 3 }, uniqueness: true

  has_many :reviews,
    -> { extending WithUserAssociationExtension },
    dependent: :destroy
    
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews
  has_many :restaurants
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index #GET
    @restaurants = Restaurant.all
  end

  def new #GET
    @restaurant = Restaurant.new
  end

  def create #POST
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show #GET
    @restaurant = Restaurant.find(params[:id])
  end

  def edit #GET
    @restaurant = Restaurant.find(params[:id])
  end

  def update #PATCH/PUT
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user == current_user
      @restaurant.update(restaurant_params)
    end
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user == current_user
      @restaurant.destroy
    end
    redirect_to restaurants_path, :flash => { :notice => "Restaurant deleted successfully" }
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new #GET
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create #POST
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    - if user_signed_in?
      = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign in", new_user_session_path
      = link_to "Sign up", new_user_registration_path
    %p(class='notice')= flash[:notice]
    %p(class='alert')= flash[:alert]
    = yield

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %p= restaurant.description
    - if restaurant.user == current_user
      %p= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
      %p= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    - if current_user && !current_user.has_reviewed?(restaurant)
      %p= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    %h2 Reviews
    - restaurant.reviews.each do |review|
      %p= review.thoughts
- else
  %h1 No restaurants yet!

%a(href=new_restaurant_path) Add a restaurant

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_field :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'